# Generated by Django 5.2.8 on 2025-12-05 19:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kurs nomi')),
                ('description', models.TextField(blank=True, verbose_name='Kurs haqida tavsifi')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Video sarlavhasi')),
                ('description', models.TextField(blank=True, verbose_name='Video tavsifi')),
                ('video_file', models.FileField(upload_to='video_lessons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])], verbose_name='Video fayli')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Video davomiyligi')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fayl hajmi (bayt)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Video Darslik',
                'verbose_name_plural': 'Video Darsliklar',
                'db_table': 'content_video_lesson',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assistant_Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('job', models.CharField(max_length=250)),
                ('experience_year', models.IntegerField(default=0)),
                ('info_knowladge', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='ustozrasm/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yordamchi Ustoz',
                'verbose_name_plural': 'Yordamchi Ustozlar',
            },
        ),
        migrations.CreateModel(
            name='High_Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('job', models.CharField(max_length=250)),
                ('experience_year', models.IntegerField(default=0)),
                ('info_knowladge', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='ustozrasm/')),
                ('notion_url', models.URLField(blank=True, help_text='Ustozning Notion sahifasi linki', null=True, validators=[django.core.validators.URLValidator()], verbose_name='Ustoz Notion URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='high_teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Katta Ustoz',
                'verbose_name_plural': 'Katta Ustozlar',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guruh nomi')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant_teacher', models.ManyToManyField(blank=True, related_name='assistant_teacher', to='course.assistant_teacher', verbose_name='Yordamchi ustozlar')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_groups', to='course.course', verbose_name='Kurs')),
                ('main_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_teacher_groups', to='course.high_teacher', verbose_name='Asosiy ustoz')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_file', models.FileField(blank=True, null=True, upload_to='student_tasks/')),
                ('comment', models.TextField(blank=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.assistant_teacher')),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
