# Generated by Django 5.2.8 on 2025-12-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('course', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='student.student'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='course',
            field=models.ManyToManyField(related_name='video_lessons', to='course.course', verbose_name='Kurs'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='group',
            field=models.ManyToManyField(blank=True, help_text="Agar hech qaysi guruh tanlanmasa , barcha guruhlar ko'rinadi", related_name='video_lessons', to='course.group', verbose_name='Guruhlar'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to='authentication.sifatchiprofile', verbose_name='Yuklagan sifatchi'),
        ),
        migrations.AddField(
            model_name='task',
            name='video_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='course.videolesson'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('course', 'name')},
        ),
    ]
