# Generated by Django 5.2.8 on 2025-12-12 15:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotionURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notion_url', models.URLField(blank=True, help_text='Ustozning Notion sahifasi linki', null=True, validators=[django.core.validators.URLValidator()], verbose_name='Ustoz Notion URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant_teacher', models.ManyToManyField(blank=True, related_name='notion_assistant_teacher', to='course.assistant_teacher', verbose_name='Yordamchi ustozlar')),
                ('main_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notion_main_teacher_groups', to='course.high_teacher', verbose_name='Asosiy ustoz')),
            ],
        ),
    ]
