# Generated by Django 5.2.8 on 2025-12-13 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_notionurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=12, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('chat_id', models.TextField(default='default_id')),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='high_teacher',
            name='notion_url',
        ),
        migrations.CreateModel(
            name='Teachercomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Komentariya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_teacher_comment', to='course.assistant_teacher', verbose_name='Yozgan Ustoz')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_comments', to='course.task', verbose_name='Vazifa')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
