# Generated by Django 5.2.8 on 2025-12-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_telegramauth_remove_high_teacher_notion_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comment',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='bosh sahifa', max_length=30),
            preserve_default=False,
        ),
    ]
