# Generated by Django 5.2.8 on 2025-12-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_knescopevideourl_delete_telegramauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Kurs nomi'),
        ),
    ]
