# Generated by Django 5.2.8 on 2025-12-26 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='video_lesson',
        ),
        migrations.AddField(
            model_name='task',
            name='kinescope_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='course.knescopevideourl'),
        ),
    ]
