# Generated by Django 5.2.8 on 2025-12-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_task_video_lesson_task_kinescope_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='score',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('yuklandi', 'Yuklandi'), ('baholandi', 'Baholandi')], default='yuklandi', max_length=20),
        ),
        migrations.AddField(
            model_name='teachercomment',
            name='score',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Qoniqarsiz'), (2, '2 - Qoniqarli'), (3, '3 - Yaxshi'), (4, '4 - Juda yaxshi'), (5, "5 - A'lo")], help_text='1 dan 5 gacha baholang', null=True, verbose_name='Baho'),
        ),
        migrations.AddField(
            model_name='teachercomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='teachercomment',
            unique_together={('task', 'assistant_teacher')},
        ),
        migrations.DeleteModel(
            name='VideoLesson',
        ),
    ]
