# Generated by Django 5.2.8 on 2026-01-01 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_task_score_task_status_teachercomment_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SifatchiProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ismi")),
                ('image', models.ImageField(blank=True, null=True, upload_to='sifatchi_images/', verbose_name='Profil rasmi')),
                ('employee_id', models.CharField(help_text='Masalan: "SP_001"', max_length=50, unique=True, verbose_name='Sifatchi ID')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name="Bo'lim")),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Sifatchi_profile', to=settings.AUTH_USER_MODEL, verbose_name='Sifat_Nazoratchi')),
            ],
            options={
                'verbose_name': 'Sifatchi Profili',
                'verbose_name_plural': 'Sifatchi Profillari',
                'db_table': 'authentication_operator_profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
