# Generated by Django 5.2.8 on 2026-01-02 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_sifatchiprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notionurl',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notion_groups', to='course.group', verbose_name='Guruh'),
        ),
    ]
