# Generated by Django 5.2.8 on 2025-12-05 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqam')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiya')),
                ('role', models.CharField(choices=[('student', 'Talaba'), ('teacher', 'Ustoz'), ('assistant', 'Yordamchi ustoz'), ('high_teacher', 'Katta ustoz'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='student', max_length=20, verbose_name='Rol')),
                ('telegram_id', models.BigIntegerField(blank=True, help_text='User birinchi marta Telegram orqali kirganda avtomatik biriktiriladi', null=True, unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi kirish')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='SifatchiProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ismi")),
                ('image', models.ImageField(blank=True, null=True, upload_to='sifatchi_images/', verbose_name='Profil rasmi')),
                ('employee_id', models.CharField(help_text='Masalan: "SP_001"', max_length=50, unique=True, verbose_name='Sifatchi ID')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name="Bo'lim")),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Yangilangan vaqt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Sifatchi_profile', to=settings.AUTH_USER_MODEL, verbose_name='Sifat_Nazoratchi')),
            ],
            options={
                'verbose_name': 'Sifatchi Profili',
                'verbose_name_plural': 'Sifatchi Profillari',
                'db_table': 'authentication_operator_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('telegram_id', models.BigIntegerField(db_index=True)),
                ('code', models.CharField(max_length=6)),
                ('code_hash', models.CharField(max_length=128)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'is_used'], name='authenticat_phone_n_afc1b4_idx'), models.Index(fields=['telegram_id', 'is_used'], name='authenticat_telegra_6b1e5a_idx'), models.Index(fields=['expires_at'], name='authenticat_expires_25786f_idx')],
            },
        ),
    ]
