# Generated by Django 5.2.8 on 2025-12-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Talaba'), ('teacher', 'Ustoz'), ('assistant_teacher', 'Yordamchi ustoz'), ('high_teacher', 'Katta ustoz'), ('admin', 'Admin'), ('superadmin', 'Super Admin'), ('Quality control', 'Sifatchi')], default='student', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='telegram_id',
            field=models.BigIntegerField(),
        ),
    ]
