# Generated by Django 5.2.8 on 2025-12-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=12, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('chat_id', models.TextField(default='default_id')),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='sifatchiprofile',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='sifatchiprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
