# Generated by Django 5.2.8 on 2026-01-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_telegramauth_alter_sifatchiprofile_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SifatchiProfile',
        ),
    ]
