# Generated by Django 5.2.8 on 2025-12-23 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_knescopevideourl_delete_telegramauth'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assigned_assistant_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_students', to='course.assistant_teacher', verbose_name='Yordamchi ustoz'),
        ),
        migrations.AlterField(
            model_name='student',
            name='assigned_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_students', to='course.course', verbose_name='Kursga tegishli talabalar'),
        ),
        migrations.AlterField(
            model_name='student',
            name='assigned_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_students', to='course.group', verbose_name='Guruhga tegishli talabalar'),
        ),
        migrations.AlterField(
            model_name='student',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, help_text='Operator tomonidan tanlanadi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='High_teacher_students', to='course.high_teacher', verbose_name='Biriktirilgan hamkor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='students/images/%Y/%m/%d/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
