# Generated by Django 5.2.8 on 2026-01-02 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_notionurl_group'),
        ('student', '0004_delete_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assigned_assistant_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_students', to='course.assistant_teacher', verbose_name='Biriktirilgan yordamchi ustoz'),
        ),
        migrations.AlterField(
            model_name='student',
            name='assigned_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_students', to='course.course', verbose_name='Talabaga tegishli kurs'),
        ),
        migrations.AlterField(
            model_name='student',
            name='assigned_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_students', to='course.group', verbose_name='Talabaga tegishli guruh'),
        ),
        migrations.AlterField(
            model_name='student',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, help_text='Operator tomonidan tanlanadi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='High_teacher_students', to='course.high_teacher', verbose_name='Biriktirilgan katta ustoz'),
        ),
        migrations.DeleteModel(
            name='StudentHistory',
        ),
    ]
