# Generated by Django 5.2.8 on 2025-12-20 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(default='Yangi suhbat', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Sessiyasi',
                'verbose_name_plural': 'Chat Sessiyalari',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '👤 Foydalanuvchi'), ('assistant', '🤖 AI Yordamchi'), ('system', '⚙️ Tizim')], default='user', max_length=20)),
                ('content', models.TextField()),
                ('ai_model', models.CharField(blank=True, max_length=50, null=True)),
                ('response_time', models.FloatField(default=0, help_text='Javob vaqti (sekund)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatai.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Xabari',
                'verbose_name_plural': 'Chat Xabarlari',
                'ordering': ['created_at'],
            },
        ),
    ]
