# Generated by Django 5.2.8 on 2025-12-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Chat Message', 'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Chat Session', 'verbose_name_plural': 'Chat Sessions'},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='ai_model',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='response_time',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='role',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='title',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chatai_chat_session_c2d029_idx'),
        ),
    ]
